# Generated by Django 4.2.16 on 2025-04-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_user_address_alter_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(null=True, upload_to='product/image')),
                ('description', models.TextField(max_length=300, null=True)),
                ('seller_id', models.IntegerField()),
                ('category', models.CharField(choices=[('milk', 'milk'), ('curd', 'curd'), ('ghee', 'ghee'), ('paneer', 'paneer'), ('other', 'other')], max_length=255)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('salescount', models.IntegerField(null=True)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
