# Generated by Django 4.2.16 on 2025-04-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], max_length=255)),
                ('user_id', models.IntegerField(null=True)),
                ('seller_id', models.IntegerField(null=True)),
                ('order_date', models.DateField(null=True)),
                ('delivered_date', models.DateField(null=True)),
                ('image', models.ImageField(null=True, upload_to='order/image')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='seller_id',
            field=models.IntegerField(null=True),
        ),
    ]
